Repository OCP-on-NERC/nerc-ocp-config, pull requests merged in 2024-10, with the labels that each got.

#549 fix: renaming the external secret yaml to match 2ti
  cluster-scope/base/external-secrets.io/externalsecrets/open-cluster-management-observability-acm-metrics-2ti-object-storage/externalsecret.yaml
Labels: bug

#559 cleanup: after creating acm-metrics-2ti
  cluster-scope/base/external-secrets.io/externalsecrets/open-cluster-management-observability-acm-metrics-object-storage/externalsecret.yaml
  cluster-scope/base/external-secrets.io/externalsecrets/open-cluster-management-observability-acm-metrics-object-storage/kustomization.yaml
  cluster-scope/base/objectbucket.io/objectbucketclaims/acm-metrics/kustomization.yaml
  cluster-scope/base/objectbucket.io/objectbucketclaims/acm-metrics/objectbucketclaim.yaml
  cluster-scope/bundles/acm-observability/kustomization.yaml
  cluster-scope/overlays/nerc-ocp-infra/acm-metrics-storage/backingstore.yaml
  cluster-scope/overlays/nerc-ocp-infra/acm-metrics-storage/bucketclass.yaml
  cluster-scope/overlays/nerc-ocp-infra/acm-metrics-storage/kustomization.yaml
  cluster-scope/overlays/nerc-ocp-infra/acm-metrics-storage/storageclass.yaml
  cluster-scope/overlays/nerc-ocp-infra/externalsecrets/open-cluster-management-observability-acm-metrics-object-storage_patch.yaml
  cluster-scope/overlays/nerc-ocp-infra/kustomization.yaml
Labels: bug, enhancement

#562 fix: acm-metrics-2ti setting new storage class
  cluster-scope/overlays/nerc-ocp-infra/acm-metrics-2ti-storage/backingstore.yaml
Labels: bug

#560 beautify: marking path be replaced in overlay
  cluster-scope/base/external-secrets.io/externalsecrets/open-cluster-management-observability-acm-metrics-2ti-object-storage/externalsecret.yaml
Labels: enhancement

#569 Adding namespace key value for zookeeper
  ai-telemetry/overlays/nerc-ocp-obs/kustomization.yaml
Labels: enhancement

#571 feat: add initial OPE dashboard grafana
  grafana/overlays/nerc-ocp-obs/grafanadashboards/kustomization.yaml
  grafana/overlays/nerc-ocp-obs/grafanadashboards/ope-metrics.yaml
  grafana/overlays/nerc-ocp-obs/kustomization.yaml
Labels: enhancement
