Repository OCP-on-NERC/nerc-ocp-config, pull requests merged in 2024-03, with the labels that each got.

#382 feat: Update loki-operator channel to stable-5.7
  cluster-scope/base/operators.coreos.com/subscriptions/loki-operator/subscription.yaml
Labels: enhancement

#394 Adding dex configuration with GRAFANA_SECRET on obs
  dex/overlays/nerc-ocp-obs/configmaps/files/config.yaml
  dex/overlays/nerc-ocp-obs/configmaps/kustomization.yaml
  dex/overlays/nerc-ocp-obs/externalsecrets/dex-clients_patch.yaml
  dex/overlays/nerc-ocp-obs/kustomization.yaml
Labels: enhancement

#385 feat: Add Grafana overlays configurations for OBS
  grafana/overlays/nerc-ocp-obs/externalsecrets/kustomization.yaml
  grafana/overlays/nerc-ocp-obs/externalsecrets/oauth-client-secret.yaml
  grafana/overlays/nerc-ocp-obs/grafanadatasources/kustomization.yaml
  grafana/overlays/nerc-ocp-obs/grafanadatasources/observability-metrics.yaml
  grafana/overlays/nerc-ocp-obs/grafanas/grafana.yaml
  grafana/overlays/nerc-ocp-obs/grafanas/kustomization.yaml
  grafana/overlays/nerc-ocp-obs/kustomization.yaml
  grafana/overlays/nerc-ocp-obs/patches/grafana-route.yaml
Labels: enhancement

#398 upgrade Loki on obs and switch Logging Operator from stable to stable-5.8 for all clusters
  cluster-scope/base/operators.coreos.com/subscriptions/cluster-logging/subscription.yaml
  cluster-scope/overlays/nerc-ocp-obs/kustomization.yaml
Labels: enhancement, operator

#396 feat: Implement OpenShift Slack alert for status updates
  cluster-scope/base/core/configmaps/thanos-ruler-custom-rules/configmap.yaml
  cluster-scope/base/external-secrets.io/externalsecrets/open-cluster-management-observability-alertmanager-config/externalsecret.yaml
Labels: enhancement

#400 Set Serverless operator version on OpenShift prod to stable-1.31 and add default KnativeServing and KnativeEventing resources
  cluster-scope/base/operators.coreos.com/subscriptions/serverless-operator/subscription.yaml
  serverless/overlays/nerc-ocp-prod/knativeeventing/knativeeventing.yaml
  serverless/overlays/nerc-ocp-prod/knativeeventing/kustomization.yaml
  serverless/overlays/nerc-ocp-prod/knativeserving/knativeserving.yaml
  serverless/overlays/nerc-ocp-prod/knativeserving/kustomization.yaml
  serverless/overlays/nerc-ocp-prod/kustomization.yaml
Labels: enhancement

#404 feat(monitoring): Add GPU-related metrics
  cluster-scope/base/core/configmaps/observability-metrics-custom-allowlist/configmap.yaml
Labels: enhancement

#408 Enable mixed MIG strategy in nerc-ocp-test cluster
  nvidia-gpu-operator/overlays/nerc-ocp-test/clusterpolicy/clusterpolicy_patch.yaml
  nvidia-gpu-operator/overlays/nerc-ocp-test/configmaps/mig-manager-config.yaml
  nvidia-gpu-operator/overlays/nerc-ocp-test/kustomization.yaml
Labels: enhancement, ope

#411 Beautify regex for GPU and DCGM metrics in custom allowlist
  cluster-scope/base/core/configmaps/observability-metrics-custom-allowlist/configmap.yaml
Labels: enhancement, good first issue

#417 style: Improve readability of 6am alerts
  cluster-scope/base/core/configmaps/thanos-ruler-custom-rules/configmap.yaml
  cluster-scope/base/external-secrets.io/externalsecrets/open-cluster-management-observability-alertmanager-config/externalsecret.yaml
Labels: enhancement, good first issue, ope

#418 fix: 6am status alert disable grouping
  cluster-scope/base/external-secrets.io/externalsecrets/open-cluster-management-observability-alertmanager-config/externalsecret.yaml
Labels: bug, ope
