Repository OCP-on-NERC/nerc-ocp-config, pull requests merged in 2024-04, with the labels that each got.

#420 Revert nvidia gpu mig strategy to single
  nvidia-gpu-operator/overlays/nerc-ocp-test/clusterpolicy/clusterpolicy_patch.yaml
Labels: operator

#421 refactor: 6am alerts - grouping, intervals, tz
  cluster-scope/base/core/configmaps/thanos-ruler-custom-rules/configmap.yaml
  cluster-scope/base/external-secrets.io/externalsecrets/open-cluster-management-observability-alertmanager-config/externalsecret.yaml
Labels: bug, enhancement, ope

#425 fix: repeat_interval cannot be zero
  cluster-scope/base/external-secrets.io/externalsecrets/open-cluster-management-observability-alertmanager-config/externalsecret.yaml
Labels: bug

#427 feat: add argocd metrics to the OBS
  cluster-scope/base/core/configmaps/observability-metrics-custom-allowlist/configmap.yaml
Labels: enhancement

#428 refactor: 6am alert update grouping and intervals
  cluster-scope/base/external-secrets.io/externalsecrets/open-cluster-management-observability-alertmanager-config/externalsecret.yaml
Labels: enhancement, ope

#429 feat: Enhance retention configuration
  cluster-scope/base/observability.open-cluster-management.io/multiclusterobservabilities/observability/multiclusterobservability.yaml
Labels: enhancement

#430 refactor: adjust 6am alerts grouping settings
  cluster-scope/base/external-secrets.io/externalsecrets/open-cluster-management-observability-alertmanager-config/externalsecret.yaml
Labels: bug, enhancement, ope

#432 fix: typo in regex for argocd metrics
  cluster-scope/base/core/configmaps/observability-metrics-custom-allowlist/configmap.yaml
Labels: bug

#435 fix: 6am status not showing each percentage
  cluster-scope/base/external-secrets.io/externalsecrets/open-cluster-management-observability-alertmanager-config/externalsecret.yaml
Labels: bug

#437 Add Ansible Automation Platform Operator bundle to nerc-ocp-test overlay
  cluster-scope/overlays/nerc-ocp-test/kustomization.yaml
Labels: operator
