Repository OCP-on-NERC/nerc-ocp-config, pull requests merged in 2024-01, with the labels that each got.

#337 Adding common, bundles, base, and secretstores
  cluster-scope/overlays/nerc-ocp-obs/clusterversion.yaml
  cluster-scope/overlays/nerc-ocp-obs/configmaps/cluster-monitoring-config.yaml
  cluster-scope/overlays/nerc-ocp-obs/externalsecrets/github-client-secret.yaml
  cluster-scope/overlays/nerc-ocp-obs/externalsecrets/github-group-sync.yaml
  cluster-scope/overlays/nerc-ocp-obs/externalsecrets/kustomization.yaml
  cluster-scope/overlays/nerc-ocp-obs/externalsecrets/rook-ceph-external-cluster-details.yaml
  cluster-scope/overlays/nerc-ocp-obs/kustomization.yaml
  cluster-scope/overlays/nerc-ocp-obs/secretstores/group-sync-operator/kustomization.yaml
  cluster-scope/overlays/nerc-ocp-obs/secretstores/kustomization.yaml
  cluster-scope/overlays/nerc-ocp-obs/secretstores/openshift-config/kustomization.yaml
  cluster-scope/overlays/nerc-ocp-obs/secretstores/openshift-ingress/kustomization.yaml
  cluster-scope/overlays/nerc-ocp-obs/secretstores/openshift-logging/kustomization.yaml
Labels: enhancement

#343 Add nerc-obs-admins to teams in kustomization.yaml
  cluster-scope/overlays/nerc-ocp-obs/kustomization.yaml
Labels: enhancement

#345 Added certs and key for grafana
  grafana/overlays/nerc-ocp-infra/externalsecrets/oauth-client-secret.yaml
  grafana/overlays/nerc-ocp-infra/grafanadatasources/observability-metrics.yaml
Labels: enhancement, question

#351 Add clusterroles rbac to obs cluster and clean-up
  cluster-scope/overlays/nerc-ocp-obs/externalsecrets/github-client-secret.yaml
  cluster-scope/overlays/nerc-ocp-obs/externalsecrets/kustomization.yaml
  cluster-scope/overlays/nerc-ocp-obs/externalsecrets/rook-ceph-external-cluster-details.yaml
  cluster-scope/overlays/nerc-ocp-obs/kustomization.yaml
Labels: bug, enhancement

#358 obs cluster default-api-certificate to use http01 issuer
  cluster-scope/overlays/nerc-ocp-obs/certificates/default-api-certificate.yaml
Labels: bug, enhancement
