Repository OCP-on-NERC/nerc-ocp-config, pull requests merged in 2024-08, with the labels that each got.

#461 feat: Update retention and concurrency for Thanos
  cluster-scope/base/observability.open-cluster-management.io/multiclusterobservabilities/observability/multiclusterobservability.yaml
Labels: bug, enhancement

#493 fix: sync gitops with manual settings
  cluster-scope/overlays/nerc-ocp-infra/acm-metrics-storage/backingstore.yaml
Labels: documentation

#497 feat: Increase Prometheus PVC storage
  cluster-scope/overlays/nerc-ocp-prod/configmaps/cluster-monitoring-config.yaml
Labels: enhancement

#498 feat: upgrd nerc-ocp-obs from 4.14.5 to 4.14.28
  cluster-scope/overlays/nerc-ocp-obs/clusterversion.yaml
Labels: enhancement

#501 fix: patch obs odf-operator from 4.13 to 4.14
  cluster-scope/overlays/nerc-ocp-obs/feature/odf/kustomization.yaml
  cluster-scope/overlays/nerc-ocp-obs/feature/odf/subscriptions/subscription-patch.yaml
Labels: enhancement

#499 feat: upgrd nerc-ocp-obs from 4.14.28 to 4.15.16
  cluster-scope/overlays/nerc-ocp-obs/clusterversion.yaml
Labels: enhancement

#502 fix: Update retentionConfig to resolve OutOfSync
  cluster-scope/base/observability.open-cluster-management.io/multiclusterobservabilities/observability/multiclusterobservability.yaml
Labels: bug

#506 feat: adding more metrics to observability
  cluster-scope/base/core/configmaps/observability-metrics-custom-allowlist/configmap.yaml
Labels: enhancement

#512 Add Fall 2024 ope course imageStream to nerc-ocp-prod
  cluster-scope/overlays/nerc-ocp-prod/kustomization.yaml
  cluster-scope/overlays/nerc-ocp-prod/rhoai/imagestreams/ucsls-F24-imagestream.yaml
  cluster-scope/overlays/nerc-ocp-prod/rhoai/kustomization.yaml
  cluster-scope/overlays/nerc-ocp-prod/rhoai/odhdashboardconfigs/kustomization.yaml
  cluster-scope/overlays/nerc-ocp-prod/rhoai/odhdashboardconfigs/odh-dashboard-config.yaml
Labels: ope
