Repository OCP-on-NERC/nerc-ocp-config, pull requests merged in 2024-02, with the labels that each got.

#360 Update X Small Resource size
  cluster-scope/overlays/nerc-ocp-prod/odhdashboardconfigs/odh-dashboard-config.yaml
Labels: enhancement, ope

#354 Configure test cluster to use loki
  logging/overlays/nerc-ocp-test/clusterlogforwarders/instance_patch.yaml
  logging/overlays/nerc-ocp-test/externalsecrets/openshift-logging-lokistack-gateway-bearer-token_patch.yaml
  logging/overlays/nerc-ocp-test/kustomization.yaml
Labels: enhancement

#366 Add Secretstore for openshift-logging in test cluster
  cluster-scope/overlays/nerc-ocp-test/secretstores/kustomization.yaml
  cluster-scope/overlays/nerc-ocp-test/secretstores/openshift-logging/kustomization.yaml
Labels: enhancement

#370 Add subscription for lokistack in obs cluster
  cluster-scope/overlays/nerc-ocp-obs/kustomization.yaml
Labels: enhancement

#374 obs: cleanup unused secretstore in openshift-storage namespace
  cluster-scope/overlays/nerc-ocp-obs/feature/odf/kustomization.yaml
  cluster-scope/overlays/nerc-ocp-obs/feature/odf/secretstores/secretstore-patch.yaml
Labels: bug, enhancement

#378 Refactor nerc-ops rbac
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/nerc-ops/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/nerc-ops/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/nerc-ops-pod-exec/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/nerc-ops-pod-exec/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/nerc-ops-portforward/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/nerc-ops-portforward/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/nerc-ops-secrets-reader/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/nerc-ops-secrets-reader/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/nerc-ops-sudoer/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/nerc-ops-sudoer/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/nerc-ops/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/nerc-ops/kustomization.yaml
  cluster-scope/bundles/nerc-ops-rbac/kustomization.yaml
  cluster-scope/overlays/common/clusterrolebindings/nerc-ops-portforward.yaml
  cluster-scope/overlays/common/clusterrolebindings/nerc-ops-sudoers.yaml
  cluster-scope/overlays/common/kustomization.yaml
Labels: enhancement

#381 nerc obs admins sudoer
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/nerc-obs-admins-sudoer/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/nerc-obs-admins-sudoer/kustomization.yaml
  cluster-scope/overlays/nerc-ocp-obs/kustomization.yaml
Labels: enhancement

#386 Post-vault-upgrade corrections
  cluster-scope/base/core/namespaces/vault/kustomization.yaml
  cluster-scope/base/core/namespaces/vault/namespace.yaml
  cluster-scope/base/external-secrets.io/clustersecretstores/nerc-cluster-secrets/clustersecretstore.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/vault-server-binding/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/vault-server-binding/kustomization.yaml
  cluster-scope/bundles/vault/kustomization.yaml
  cluster-scope/overlays/nerc-ocp-infra/kustomization.yaml
  dex/overlays/nerc-ocp-infra/configmaps/files/config.yaml
  vault/backup-job/base/scripts/create-snapshot.sh
  vault/instance/overlays/nerc-ocp-infra/vault-compat-route.yaml
Labels: bug, enhancement

#379 feat: Update alerts for ope classes
  cluster-scope/base/core/configmaps/thanos-ruler-custom-rules/configmap.yaml
  cluster-scope/base/external-secrets.io/externalsecrets/open-cluster-management-observability-alertmanager-config/externalsecret.yaml
Labels: enhancement, ope
