Repository OCP-on-NERC/nerc-ocp-config, pull requests merged in 2025-09, with the labels that each got.

#785 Fix AlertManager routing for 6:05am status alerts
  cluster-scope/base/external-secrets.io/externalsecrets/open-cluster-management-observability-alertmanager-config/externalsecret.yaml
Labels: bug

#793 ocp-test: upgrade RHOAI to most recent version
  cluster-scope/overlays/nerc-ocp-test/feature/rhoai/subscriptions/subscription-patch.yaml
Labels: operator

#801 nerc-ocp-infra: update ODF operator channel to stable-4.19
  cluster-scope/overlays/nerc-ocp-infra/feature/odf/subscriptions/subscription-patch.yaml
Labels: enhancement
